### ISSUE TITLE
Does not convert gifs on tumblr and also breaks direct post opening.

### ISSUE THREAD

**Issue by ghost** [thomasandersen/gfycat-companion-for-firefox#1]
Example post: http://gifthescreen.tumblr.com/post/74487827849

**Comment by godofgrunts** [comment]
Can confirm. Having this issue as well.

**Comment by thomasandersen** [comment]
Hi
The add-on does not convert gifs that are inlined on the page. At the moment it is no convenient way to convert batches of files with the gfycat service as there is a file conversion limit pr. minute. 

The way tumbler displays an image is not a "direct" request. Tumblr loads the image in a modal window which is not handled at the moment. 
We have some support for the Reddit Enhancement Suite which of-course only works with Reddit. We may add something similar for Tumblr in the future. If you have any ideas, please feel free to discuss them.
